var FontInspector=function(){function g(){for(var b=document.querySelectorAll("div[data-font-name]"),c=0,a=b.length;c<a;++c)b[c].className="debuggerHideText"}function h(b,c){for(var a=document.querySelectorAll("div[data-font-name="+b+"]"),f=0,d=a.length;f<d;++f)a[f].className=c?"debuggerShowText":"debuggerHideText"}function d(b){if(b.target.dataset.fontName&&"DIV"===b.target.tagName.toUpperCase()){b=b.target.dataset.fontName;for(var c=document.getElementsByTagName("input"),a=0;a<c.length;++a){var f=
c[a];f.dataset.fontName==b&&(f.checked=!f.checked,h(b,f.checked),f.scrollIntoView())}}}var e,a=!1;return{id:"FontInspector",name:"Font Inspector",panel:null,manager:null,init:function(){var b=this.panel;b.setAttribute("style","padding: 5px;");var c=document.createElement("button");c.addEventListener("click",g);c.textContent="Refresh";b.appendChild(c);e=document.createElement("div");b.appendChild(e)},cleanup:function(){e.textContent=""},enabled:!1,get active(){return a},set active(b){if(a=b)document.body.addEventListener("click",
d,!0),g();else{document.body.removeEventListener("click",d,!0);b=document.querySelectorAll("div[data-font-name]");for(var c=0,k=b.length;c<k;++c)b[c].className=""}},fontAdded:function(b,c){var a=function(b,c){for(var a=document.createElement("table"),d=0;d<c.length;d++){var f=document.createElement("tr"),k=document.createElement("td");k.textContent=c[d];f.appendChild(k);k=document.createElement("td");k.textContent=b[c[d]].toString();f.appendChild(k);a.appendChild(f)}return a}(b,["name","type"]),f=
/url\(['"]?([^\)"']+)/.exec(c),d=b.loadedName,l=document.createElement("div"),r=document.createElement("span");r.textContent=d;var q=document.createElement("a");q.href=f[1];q.textContent="Download";f=document.createElement("a");f.href="";f.textContent="Log";f.addEventListener("click",function(c){c.preventDefault();console.log(b)});var m=document.createElement("input");m.setAttribute("type","checkbox");m.dataset.fontName=d;m.addEventListener("click",function(b,c){return function(){h(c,b.checked)}}(m,
d));l.appendChild(m);l.appendChild(r);l.appendChild(document.createTextNode(" "));l.appendChild(q);l.appendChild(document.createTextNode(" "));l.appendChild(f);l.appendChild(a);e.appendChild(l);setTimeout(function(){this.active&&g()}.bind(this),2E3)}}}(),StepperManager=function(){var g=[],h=null,d=null,e=null,a={};return{id:"Stepper",name:"Stepper",panel:null,manager:null,init:function(){var b=this;this.panel.setAttribute("style","padding: 5px;");d=document.createElement("div");e=document.createElement("select");
e.addEventListener("change",function(c){b.selectStepper(this.value)});d.appendChild(e);h=document.createElement("div");this.panel.appendChild(d);this.panel.appendChild(h);sessionStorage.getItem("pdfjsBreakPoints")&&(a=JSON.parse(sessionStorage.getItem("pdfjsBreakPoints")))},cleanup:function(){e.textContent="";h.textContent="";g=[]},enabled:!1,active:!1,create:function(b){var c=document.createElement("div");c.id="stepper"+b;c.setAttribute("hidden",!0);c.className="stepper";h.appendChild(c);var d=document.createElement("option");
d.textContent="Page "+(b+1);d.value=b;e.appendChild(d);c=new Stepper(c,b,a[b]||[]);g.push(c);1===g.length&&this.selectStepper(b,!1);return c},selectStepper:function(b,c){var a;c&&this.manager.selectPanel(this);for(a=0;a<g.length;++a){var d=g[a];d.pageIndex==b?d.panel.removeAttribute("hidden"):d.panel.setAttribute("hidden",!0)}d=e.options;for(a=0;a<d.length;++a){var p=d[a];p.selected=p.value==b}},saveBreakPoints:function(b,c){a[b]=c;sessionStorage.setItem("pdfjsBreakPoints",JSON.stringify(a))}}}(),
Stepper=function(){function g(a,b){var c=document.createElement(a);b&&(c.textContent=b);return c}function h(a){if("string"===typeof a)return 75>=a.length?a:a.substr(0,75)+"...";if("object"!==typeof a||null===a)return a;if("length"in a){var b=[],c,d;c=0;for(d=Math.min(10,a.length);c<d;c++)b.push(h(a[c]));c<a.length&&b.push("...");return b}b={};for(c in a)b[c]=h(a[c]);return b}function d(a,b,c){this.panel=a;this.breakPoint=0;this.nextBreakPoint=null;this.pageIndex=b;this.breakPoints=c;this.currentIdx=
-1;this.operatorListIdx=0}var e=null;d.prototype={init:function(){var a=this.panel,b=g("div","c=continue, s=step"),c=g("table");b.appendChild(c);c.cellSpacing=0;var d=g("tr");c.appendChild(d);d.appendChild(g("th","Break"));d.appendChild(g("th","Idx"));d.appendChild(g("th","fn"));d.appendChild(g("th","args"));a.appendChild(b);this.table=c;if(!e){e=Object.create(null);for(var f in PDFJS.OPS)e[PDFJS.OPS[f]]=f}},updateOperatorList:function(a){function b(){var b=+this.dataset.idx;this.checked?c.breakPoints.push(b):
c.breakPoints.splice(c.breakPoints.indexOf(b),1);StepperManager.saveBreakPoints(c.pageIndex,c.breakPoints)}var c=this;if(!(15E3<this.operatorListIdx)){for(var d=document.createDocumentFragment(),f=Math.min(15E3,a.fnArray.length),p=this.operatorListIdx;p<f;p++){var l=g("tr");l.className="line";l.dataset.idx=p;d.appendChild(l);var r=-1!=this.breakPoints.indexOf(p),q=a.argsArray[p]||[],m=g("td"),n=g("input");n.type="checkbox";n.className="points";n.checked=r;n.dataset.idx=p;n.onclick=b;m.appendChild(n);
l.appendChild(m);l.appendChild(g("td",p.toString()));r=e[a.fnArray[p]];m=q;if("showText"===r){for(var q=q[0],m=[],n=[],t=0;t<q.length;t++){var s=q[t];"object"===typeof s&&null!==s?n.push(s.fontChar):(0<n.length&&(m.push(n.join("")),n=[]),m.push(s))}0<n.length&&m.push(n.join(""));m=[m]}l.appendChild(g("td",r));l.appendChild(g("td",JSON.stringify(h(m))))}f<a.fnArray.length&&(l=g("tr"),f=g("td","..."),f.colspan=4,d.appendChild(f));this.operatorListIdx=a.fnArray.length;this.table.appendChild(d)}},getNextBreakPoint:function(){this.breakPoints.sort(function(b,
a){return b-a});for(var a=0;a<this.breakPoints.length;a++)if(this.breakPoints[a]>this.currentIdx)return this.breakPoints[a];return null},breakIt:function(a,b){StepperManager.selectStepper(this.pageIndex,!0);var c=this,d=document;c.currentIdx=a;var f=function(a){switch(a.keyCode){case 83:d.removeEventListener("keydown",f,!1);c.nextBreakPoint=c.currentIdx+1;c.goTo(-1);b();break;case 67:d.removeEventListener("keydown",f,!1),a=c.getNextBreakPoint(),c.nextBreakPoint=a,c.goTo(-1),b()}};d.addEventListener("keydown",
f,!1);c.goTo(a)},goTo:function(a){for(var b=this.panel.getElementsByClassName("line"),c=0,d=b.length;c<d;++c){var f=b[c];f.dataset.idx==a?(f.style.backgroundColor="rgb(251,250,207)",f.scrollIntoView()):f.style.backgroundColor=null}}};return d}(),Stats=function(){function g(d){for(;d.hasChildNodes();)d.removeChild(d.lastChild)}function h(e){for(var a=0,b=d.length;a<b;++a)if(d[a].pageNumber===e)return a;return!1}var d=[];return{id:"Stats",name:"Stats",panel:null,manager:null,init:function(){this.panel.setAttribute("style",
"padding: 5px;");PDFJS.enableStats=!0},enabled:!1,active:!1,add:function(e,a){if(a){var b=h(e);!1!==b&&(this.panel.removeChild(d[b].div),d.splice(b,1));b=document.createElement("div");b.className="stats";var c=document.createElement("div");c.className="title";c.textContent="Page: "+e;var k=document.createElement("div");k.textContent=a.toString();b.appendChild(c);b.appendChild(k);d.push({pageNumber:e,div:b});d.sort(function(a,b){return a.pageNumber-b.pageNumber});g(this.panel);b=0;for(c=d.length;b<
c;++b)this.panel.appendChild(d[b].div)}},cleanup:function(){d=[];g(this.panel)}}}(),PDFBug=function(){var g=[],h=null;return{tools:[FontInspector,StepperManager,Stats],enable:function(d){var e=!1,a=this.tools;1===d.length&&"all"===d[0]&&(e=!0);for(var b=0;b<a.length;++b){var c=a[b];if(e||-1!==d.indexOf(c.id))c.enabled=!0}e||a.sort(function(b,c){var e=d.indexOf(b.id),e=0>e?a.length:e,g=d.indexOf(c.id),g=0>g?a.length:g;return e-g})},init:function(){var d=document.createElement("div");d.id="PDFBug";
var e=document.createElement("div");e.setAttribute("class","controls");d.appendChild(e);var a=document.createElement("div");a.setAttribute("class","panels");d.appendChild(a);var b=document.getElementById("viewerContainer");b.appendChild(d);b.style.right="300px";for(var d=this.tools,c=this,b=0;b<d.length;++b){var k=d[b],f=document.createElement("div"),h=document.createElement("button");h.textContent=k.name;h.addEventListener("click",function(a){return function(b){b.preventDefault();c.selectPanel(a)}}(b));
e.appendChild(h);a.appendChild(f);k.panel=f;k.manager=this;k.enabled?k.init():f.textContent=k.name+' is disabled. To enable add  "'+k.id+'" to the pdfBug parameter and refresh (seperate multiple by commas).';g.push(h)}this.selectPanel(0)},cleanup:function(){for(var d=0,e=this.tools.length;d<e;d++)this.tools[d].enabled&&this.tools[d].cleanup()},selectPanel:function(d){"number"!==typeof d&&(d=this.tools.indexOf(d));if(d!==h){h=d;for(var e=this.tools,a=0;a<e.length;++a)a==d?(g[a].setAttribute("class",
"active"),e[a].active=!0,e[a].panel.removeAttribute("hidden")):(g[a].setAttribute("class",""),e[a].active=!1,e[a].panel.setAttribute("hidden","true"))}}}}();
