document.webL10n=function(C,h,H){function D(){var c=h.querySelector('script[type="application/l10n"]');return c?JSON.parse(c.innerHTML):null}function x(c){var d=h.createEvent("Event");d.initEvent("localized",!0,!1);d.language=c;h.dispatchEvent(d)}function y(c,d,b,e){d=d||function(a){};b=b||function(){console.warn(c+" not found.")};var f=new XMLHttpRequest;f.open("GET",c,e);f.overrideMimeType&&f.overrideMimeType("text/plain; charset=utf-8");f.onreadystatechange=function(){4==f.readyState&&(200==f.status||
0===f.status?d(f.responseText):b())};f.onerror=b;f.ontimeout=b;try{f.send(null)}catch(a){b()}}function E(c,d,b,e){function f(b){function c(b,n){for(var v=b.replace(g,"").split(/[\r\n]+/),t="*",u=d.replace(/-[a-z]+$/i,""),t=!1,w="",r=0;r<v.length;r++){var l=v[r];if(!q.test(l)){if(n){if(h.test(l)){w=h.exec(l);t=w[1];t="*"!==t&&t!==d&&t!==u;continue}else if(t)continue;k.test(l)&&(w=k.exec(l),e(a+w[1]))}(l=l.match(s))&&3==l.length&&(w=l[1],l=l[2],l=0>l.lastIndexOf("\\")?l:l.replace(/\\\\/g,"\\").replace(/\\n/g,
"\n").replace(/\\r/g,"\r").replace(/\\t/g,"\t").replace(/\\b/g,"\b").replace(/\\f/g,"\f").replace(/\\{/g,"{").replace(/\\}/g,"}").replace(/\\"/g,'"').replace(/\\'/g,"'"),f[w]=l)}}}function e(a){y(a,function(a){c(a,!1)},null,!1)}var f=[],g=/^\s*|\s*$/,q=/^\s*#|^\s*$/,h=/^\s*\[(.*)\]\s*$/,k=/^\s*@import\s+url\((.*)\)\s*$/i,s=/^([^=\s]*)\s*=\s*(.+)$/;c(b,!0);return f}var a=c.replace(/[^\/]*$/,"")||"./";y(c,function(a){r+=a;a=f(a);for(var c in a){var d,e;e=c.lastIndexOf(".");0<e?(d=c.substring(0,e),e=
c.substr(e+1)):(d=c,e="textContent");g[d]||(g[d]={});g[d][e]=a[c]}b&&b()},e,!0)}function F(c,d){function b(a){var b=a.href;this.load=function(a,c){var d=a;E(b,a,c,function(){console.warn(b+" not found.");d=""});return d}}d=d||function(){};g={};k=r="";k=c;var e=h.querySelectorAll('link[type="application/l10n"]'),f=e.length;if(0===f)(e=D())&&e.locales&&e.default_locale?(console.log("using the embedded JSON directory, early way out"),g=e.locales[c]||e.locales[e.default_locale],d()):console.log("no resource to load, early way out"),
x(c),u="complete";else for(var a=null,n=0,a=function(){n++;n>=f&&(d(),x(c),u="complete")},v=0;v<f;v++)(new b(e[v])).load(c,a)!=c&&(console.warn('"'+c+'" resource not found'),k="")}function G(c){function d(a,b){return-1!==b.indexOf(a)}function b(a,b,c){return b<=a&&a<=c}var e={0:function(a){return"other"},1:function(a){return b(a%100,3,10)?"few":0===a?"zero":b(a%100,11,99)?"many":2==a?"two":1==a?"one":"other"},2:function(a){return 0!==a&&0===a%10?"many":2==a?"two":1==a?"one":"other"},3:function(a){return 1==
a?"one":"other"},4:function(a){return b(a,0,1)?"one":"other"},5:function(a){return b(a,0,2)&&2!=a?"one":"other"},6:function(a){return 0===a?"zero":1==a%10&&11!=a%100?"one":"other"},7:function(a){return 2==a?"two":1==a?"one":"other"},8:function(a){return b(a,3,6)?"few":b(a,7,10)?"many":2==a?"two":1==a?"one":"other"},9:function(a){return 0===a||1!=a&&b(a%100,1,19)?"few":1==a?"one":"other"},10:function(a){return b(a%10,2,9)&&!b(a%100,11,19)?"few":1!=a%10||b(a%100,11,19)?"other":"one"},11:function(a){return b(a%
10,2,4)&&!b(a%100,12,14)?"few":0===a%10||b(a%10,5,9)||b(a%100,11,14)?"many":1==a%10&&11!=a%100?"one":"other"},12:function(a){return b(a,2,4)?"few":1==a?"one":"other"},13:function(a){return b(a%10,2,4)&&!b(a%100,12,14)?"few":1!=a&&b(a%10,0,1)||b(a%10,5,9)||b(a%100,12,14)?"many":1==a?"one":"other"},14:function(a){return b(a%100,3,4)?"few":2==a%100?"two":1==a%100?"one":"other"},15:function(a){return 0===a||b(a%100,2,10)?"few":b(a%100,11,19)?"many":1==a?"one":"other"},16:function(a){return 1==a%10&&11!=
a?"one":"other"},17:function(a){return 3==a?"few":0===a?"zero":6==a?"many":2==a?"two":1==a?"one":"other"},18:function(a){return 0===a?"zero":b(a,0,2)&&0!==a&&2!=a?"one":"other"},19:function(a){return b(a,2,10)?"few":b(a,0,1)?"one":"other"},20:function(a){return!b(a%10,3,4)&&9!=a%10||b(a%100,10,19)||b(a%100,70,79)||b(a%100,90,99)?0===a%1E6&&0!==a?"many":2!=a%10||d(a%100,[12,72,92])?1!=a%10||d(a%100,[11,71,91])?"other":"one":"two":"few"},21:function(a){return 0===a?"zero":1==a?"one":"other"},22:function(a){return b(a,
0,1)||b(a,11,99)?"one":"other"},23:function(a){return b(a%10,1,2)||0===a%20?"one":"other"},24:function(a){return b(a,3,10)||b(a,13,19)?"few":d(a,[2,12])?"two":d(a,[1,11])?"one":"other"}},f={af:3,ak:4,am:4,ar:1,asa:3,az:0,be:11,bem:3,bez:3,bg:3,bh:4,bm:0,bn:3,bo:0,br:20,brx:3,bs:11,ca:3,cgg:3,chr:3,cs:12,cy:17,da:3,de:3,dv:3,dz:0,ee:3,el:3,en:3,eo:3,es:3,et:3,eu:3,fa:0,ff:5,fi:3,fil:4,fo:3,fr:5,fur:3,fy:3,ga:8,gd:24,gl:3,gsw:3,gu:3,guw:4,gv:23,ha:3,haw:3,he:2,hi:4,hr:11,hu:0,id:0,ig:0,ii:0,is:3,it:3,
iu:7,ja:0,jmc:3,jv:0,ka:0,kab:5,kaj:3,kcg:3,kde:0,kea:0,kk:3,kl:3,km:0,kn:0,ko:0,ksb:3,ksh:21,ku:3,kw:7,lag:18,lb:3,lg:3,ln:4,lo:0,lt:10,lv:6,mas:3,mg:4,mk:16,ml:3,mn:3,mo:9,mr:3,ms:0,mt:15,my:0,nah:3,naq:7,nb:3,nd:3,ne:3,nl:3,nn:3,no:3,nr:3,nso:4,ny:3,nyn:3,om:3,or:3,pa:3,pap:3,pl:13,ps:3,pt:3,rm:3,ro:9,rof:3,ru:11,rwk:3,sah:0,saq:3,se:7,seh:3,ses:0,sg:0,sh:11,shi:19,sk:12,sl:14,sma:7,smi:7,smj:7,smn:7,sms:7,sn:3,so:3,sq:3,sr:11,ss:3,ssy:3,st:3,sv:3,sw:3,syr:3,ta:3,te:3,teo:3,th:0,ti:4,tig:3,tk:3,
tl:4,tn:3,to:0,tr:0,ts:3,tzm:22,uk:11,ur:3,ve:3,vi:0,vun:3,wa:4,wae:3,wo:0,xh:3,xog:3,yo:0,zh:0,zu:3}[c.replace(/-.*$/,"")];return f in e?e[f]:(console.warn("plural form unknown for ["+c+"]"),function(){return"other"})}function z(c,d,b){var e=g[c];if(!e){console.warn("#"+c+" is undefined.");if(!b)return null;e=b}b={};for(var f in e){var a=e[f];var n=d,h=c,k=f,m=/\{\[\s*([a-zA-Z]+)\(([a-zA-Z]+)\)\s*\]\}/.exec(a);if(m&&m.length){var p=m[1],m=m[2],q=void 0;n&&m in n?q=n[m]:m in g&&(q=g[m]);p in s&&(a=
(0,s[p])(a,q,h,k))}a:for(n=d,h=c,k=/\{\{\s*(.+?)\s*\}\}/,p=k.exec(a);p;){if(!p||2>p.length)break a;m=p[1];q="";if(n&&m in n)q=n[m];else if(m in g)q=g[m].textContent;else{console.log("argument {{"+m+"}} for #"+h+" is undefined.");break a}a=a.substring(0,p.index)+q+a.substr(p.index+p[0].length);p=k.exec(a)}b[f]=a}return b}function A(c){var d,b;if(c){d=c.getAttribute("data-l10n-id");var e=c.getAttribute("data-l10n-args");b={};if(e)try{b=JSON.parse(e)}catch(f){console.warn("could not parse arguments for #"+
d)}}else b=d=void 0;if(d)if(b=z(d,b)){if(b.textContent){if(c.children)d=c.children.length;else if("undefined"!==typeof c.childElementCount)d=c.childElementCount;else for(e=d=0;e<c.childNodes.length;e++)d+=1===c.nodeType?1:0;if(0===d)c.textContent=b.textContent;else{d=c.childNodes;for(var e=!1,a=0,g=d.length;a<g;a++)3===d[a].nodeType&&/\S/.test(d[a].nodeValue)&&(e?d[a].nodeValue="":(d[a].nodeValue=b.textContent,e=!0));e||(d=h.createTextNode(b.textContent),c.insertBefore(d,c.firstChild))}delete b.textContent}for(var k in b)c[k]=
b[k]}else console.warn("#"+d+" is undefined.")}function B(c){for(var d=(c=c||h.documentElement)?c.querySelectorAll("*[data-l10n-id]"):[],b=d.length,e=0;e<b;e++)A(d[e]);A(c)}var g={},r="",k="",s={},u="loading";s.plural=function(c,d,b,e){d=parseFloat(d);if(isNaN(d)||"textContent"!=e)return c;s._pluralRules||(s._pluralRules=G(k));var f="["+s._pluralRules(d)+"]";0===d&&b+"[zero]"in g?c=g[b+"[zero]"][e]:1==d&&b+"[one]"in g?c=g[b+"[one]"][e]:2==d&&b+"[two]"in g?c=g[b+"[two]"][e]:b+f in g?c=g[b+f][e]:b+
"[other]"in g&&(c=g[b+"[other]"][e]);return c};return{get:function(c,d,b){var e=c.lastIndexOf("."),f="textContent";0<e&&(f=c.substr(e+1),c=c.substring(0,e));var a;b&&(a={},a[f]=b);return(d=z(c,d,a))&&f in d?d[f]:"{{"+c+"}}"},getData:function(){return g},getText:function(){return r},getLanguage:function(){return k},setLanguage:function(c){F(c,B)},getDirection:function(){return 0<="ar ar-sa he fa ps ur".split(" ").indexOf(k)?"rtl":"ltr"},translate:B,getReadyState:function(){return u},ready:function(c){c&&
("complete"==u||"interactive"==u?C.setTimeout(c):h.addEventListener?h.addEventListener("localized",c):h.attachEvent&&h.documentElement.attachEvent("onpropertychange",function(d){"localized"===d.propertyName&&c()}))}}}(window,document);
